name: ISW2 Testing OpenJPA JaCoCo

on:
  push:
    branches:
      - isw2
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0.372
          distribution: 'adopt'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # I'm working whit java 8 and sonar plugin not work with this java version, so I've commented the following run cmd
        # run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Andrea041_openjpa -P JaCoCo
        run: mvn clean verify -P JaCoCo
      - name: Save JaCoCo report
        uses: actions/upload-artifact@v3
        with:
          name: JaCoCoReport
          path: report-collector/target/site/jacoco-aggregate/